Create DATABASE ProjetoVeiculo
GO

USE ProjetoVeiculo
GO

CREATE TABLE Usuario(
	IdUsuario VARCHAR(40) PRIMARY KEY,
	Senha VARCHAR(60) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) NOT NULL,
);
GO

CREATE TABLE Genero(
	IdGenero VARCHAR(40) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE Veiculos(
	IdVeiculos VARCHAR(40) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Imagem VARCHAR(100),
	IdGenero VARCHAR(40) FOREIGN KEY REFERENCES Genero(IdGenero)
);
GO
